const eventsData = [
  {
    event: {
      id: 123,
      title: 'Sea-inspired paintings on exhibit',
      url: 'http://blogs.oregonstate.edu/testo',
      updated_at: '2019-06-13T05:47:48-07:00',
      created_at: '2019-04-08T11:42:14-07:00',
      facebook_id: null,
      first_date: '2019-05-28',
      last_date: '2019-07-07',
      hashtag: '',
      urlname: 'sea-inspired_paintings',
      user_id: 123,
      directions: '',
      allows_reviews: true,
      allows_attendance: true,
      location: '',
      room_number: 'Visitor Center',
      location_name: 'Hatfield Marine Science Center',
      created_by: 123,
      updated_by: 123,
      city_id: null,
      neighborhood_id: null,
      school_id: 123,
      campus_id: 123,
      recurring: true,
      free: true,
      private: false,
      verified: true,
      rejected: false,
      sponsored: false,
      venue_id: 123,
      ticket_url: '',
      ticket_cost: 'free, donation ',
      keywords: [],
      tags: [],
      description_text:
        'A new exhibit of five paintings by Mimi Cernyar Fox is on display through July 7 at the Hatfield Visitor Center in Newport. The pieces represent the sea and coastal mudflats of the PNW and are created using oil, acrylic, and charcoal on canvas.',
      photo_id: 213,
      detail_views: 123,
      address: '123 Marine Science Dr, Newport, OR 97365',
      description:
        '<p>A new exhibit of five paintings by Mimi Cernyar Fox is on display through July 7 at the Hatfield Visitor Center in Newport. The pieces represent the sea and coastal mudflats of the PNW and are created using oil, acrylic, and charcoal on canvas.</p>\r\n',
      featured: false,
      localist_url:
        'https://events.oregonstate.edu/event/sea-inspired_paintings_on_exhibit_at_hatfield_visitor_center_until_july_7',
      localist_ics_url:
        'https://events.oregonstate.edu/event/sea-inspired_paintings_on_exhibit_at_hatfield_visitor_center_until_july_7.ics',
      photo_url:
        'https://images.localist.com/photos/849707/huge/dc9bddd1554ee9119d1109f337d82d700118bba1.jpg',
      venue_url: 'https://events.oregonstate.edu/hatfield_marine_science_center'
    }
  },
  {
    event: {
      id: 1234,
      title: 'Pathogen Environmental Monitoring Workshop for Pacific Northwest Food Ind',
      url: 'https://www.eventbrite.com/e/pathogen',
      updated_at: '2019-06-13T05:37:44-07:00',
      created_at: '2019-05-25T13:46:08-07:00',
      facebook_id: null,
      first_date: '2019-06-12',
      last_date: '2019-06-13',
      hashtag: 'Food Safety, Food Producers',
      urlname: 'pathogen_environmental',
      user_id: 123,
      directions: '',
      allows_reviews: true,
      allows_attendance: true,
      location: '',
      room_number: '',
      location_name: 'Food Innovation Center',
      created_by: 123,
      updated_by: 123,
      city_id: null,
      neighborhood_id: null,
      school_id: 123,
      campus_id: 123,
      recurring: false,
      free: true,
      private: false,
      verified: true,
      rejected: false,
      sponsored: false,
      venue_id: 123,
      ticket_url: 'https://www.eventbrite.com/e/testo',
      ticket_cost: '',
      keywords: [],
      tags: [],
      description_text:
        'Food processing, handling and storage facilities can create\nconditions that allow microorganisms to become established and\nthrive. Some of these microorganisms have the potential to\ncause foodborne illness if they contaminate food products.\nIdentifying niche locations and hotspots that house these\nmicroorganisms through both routine and investigative\nenvironmental programs is critical for producers of ready-to-\neat foods and raw agricultural commodities.\n\nThis two-day workshop is intended to provide you\nwith knowledge and best practices on developing and\nimplementing an effective Pathogen Environmental\nMonitoring (PEM) program.\nWhat to expect?\n● Through hands-on activities you will:\n- Become familiar with environmental foodborne pathogens,\n- Learn how to collect swabs,\n- Identify issues through case studies from the industry,\n- Get tips on how to design and establish a PEM program,\n- Have opportunity to discuss effective controls and\ncorrective action steps in small working groups.\n\n● You will receive:\n- All course materials,\n- Certificate of course attendance,\n- Meals (lunch and refreshments).\n\nREGISTRATION:\nThis workshop is subsidized through OR SCBGP\ngrant ODA-5010-GR.\nPlease note:\nRegistrations are limited. NO substitutions,\ntransfers, or refunds will be issued within one week\nof the training start date.\n\n● Register through Eventbrite\nhttps://www.eventbrite.com/e/pathogen-environmental-monitoring-workshop-tickets-61456616394\n\n\n● Cost:\n$150 per person,\n$125 for multiple registrations\n\nWHEN AND WHERE?\n● Location:\nFood Innovation Center\n1207 NW Naito Parkway, Portland, OR 97209\n● Dates and times:\nDay 1: June 12, 2019 8:00 AM to 5:00 PM\nDay 2: June 13, 2019 8:00 AM to 3:00 PM\n\nJovana Kovacevic\nAssistant Professor and Food Safety Extension Specialist\nOSU Food Innovation Center, Portland OR\njovana.kovacevic@oregonstate.edu | 503.872.6621\n\n\nJoy Waite-Cusic\nAssociate Professor of Food Safety Systems\nOSU Dept. Food Science and Technology, Corvallis OR\njoy.waite-cusic@oregonstate.edu | 541.737.6825\n\nJohn Jorgensen\nGraduate Student, OSU FIC/FST, Portland, OR\njohn.jorgensen@oregonstate.edu',
      photo_id: 123,
      detail_views: 34,
      address: '1207 NW Naito Parkway, Portland, OR 97209',
      description:
        '<div>Food processing, handling and storage facilities can create<br />\r\nconditions that allow microorganisms to become established and<br />\r\nthrive. Some of these microorganisms have the potential to<br />\r\ncause foodborne illness if they contaminate food products.<br />\r\nIdentifying niche locations and hotspots that house these<br />\r\nmicroorganisms through both routine and investigative<br />\r\nenvironmental programs is critical for producers of ready-to-<br />\r\neat foods and raw agricultural commodities.<br />\r\n<br />\r\nThis two-day workshop is intended to provide you<br />\r\nwith knowledge and best practices on developing and<br />\r\nimplementing an effective Pathogen Environmental<br />\r\nMonitoring (PEM) program.</div>\r\n\r\n<p><br />\r\n<b>What to expect?</b><br />\r\n● Through hands-on activities you will:<br />\r\n- Become familiar with environmental foodborne pathogens,<br />\r\n- Learn how to collect swabs,<br />\r\n- Identify issues through case studies from the industry,<br />\r\n- Get tips on how to design and establish a PEM program,<br />\r\n- Have opportunity to discuss effective controls and<br />\r\ncorrective action steps in small working groups.<br />\r\n<br />\r\n<b>● You will receive:</b><br />\r\n- All course materials,<br />\r\n- Certificate of course attendance,<br />\r\n- Meals (lunch and refreshments).<br />\r\n<br />\r\n<b>REGISTRATION:</b><br />\r\nThis workshop is subsidized through OR SCBGP<br />\r\ngrant ODA-5010-GR.<br />\r\n<i>Please note:</i><br />\r\nRegistrations are limited. NO substitutions,<br />\r\ntransfers, or refunds will be issued within one week<br />\r\nof the training start date.<br />\r\n<br />\r\n● Register through Eventbrite<br />\r\n<a href="https://www.eventbrite.com/e/pathogen-environmental-monitoring-workshop-tickets-61456616394">https://www.eventbrite.com/e/pathogen-environmental-monitoring-workshop-tickets-61456616394</a></p>\r\n\r\n<p><br />\r\n● Cost:<br />\r\n$150 per person,<br />\r\n$125 for multiple registrations<br />\r\n<br />\r\n<b>WHEN AND WHERE?</b><br />\r\n● Location:<br />\r\nFood Innovation Center<br />\r\n1207 NW Naito Parkway, Portland, OR 97209<br />\r\n● Dates and times:<br />\r\nDay 1: June 12, 2019 8:00 AM to 5:00 PM<br />\r\nDay 2: June 13, 2019 8:00 AM to 3:00 PM<br />\r\n<br />\r\n<b>Jovana Kovacevic</b><br />\r\nAssistant Professor and Food Safety Extension Specialist<br />\r\nOSU Food Innovation Center, Portland OR<br />\r\njovana.kovacevic@oregonstate.edu | 503.872.6621</p>\r\n\r\n<p><br />\r\n<b>Joy Waite-Cusic</b><br />\r\nAssociate Professor of Food Safety Systems<br />\r\nOSU Dept. Food Science and Technology, Corvallis OR<br />\r\njoy.waite-cusic@oregonstate.edu | 541.737.6825<br />\r\n<br />\r\n<b>John Jorgensen</b><br />\r\nGraduate Student, OSU FIC/FST, Portland, OR<br />\r\njohn.jorgensen@oregonstate.edu</p>\r\n',
      featured: false,
      localist_url: 'https://events.oregonstate.edu/event/pathogetesto',
      localist_ics_url: 'https://events.oregonstate.edu/event/testo.ics',
      photo_url: 'https://images.localist.com/photos/30318536347604/huge/testo.jpg',
      venue_url: 'https://events.oregonstate.edu/testo'
    }
  },
  {
    event: {
      id: 12345,
      title: 'Katherine Dziedzic - Integrative Biology PhD Defense Seminar',
      url: '',
      updated_at: '2019-06-13T05:49:02-07:00',
      created_at: '2019-06-03T14:56:22-07:00',
      facebook_id: null,
      first_date: '2019-06-13',
      last_date: '2019-06-13',
      hashtag: '',
      urlname: 'katherine_dziedzic',
      user_id: 123,
      directions: '',
      allows_reviews: true,
      allows_attendance: true,
      location: '',
      room_number: '123',
      location_name: 'Agricultural & Life Sciences Building',
      created_by: 123,
      updated_by: 123,
      city_id: null,
      neighborhood_id: null,
      school_id: 123,
      campus_id: 123,
      recurring: false,
      free: true,
      private: false,
      verified: true,
      rejected: false,
      sponsored: false,
      venue_id: 123,
      ticket_url: '',
      ticket_cost: '',
      keywords: [],
      tags: [],
      description_text:
        '"Thermal tolerance and adaptation in cnidarians: an investigation of host transcriptomic responses and heritable variation across natural populations"',
      photo_id: 123,
      detail_views: 22,
      address: '2750 SW Campus Way, Corvallis, OR 97331',
      description:
        '<p><span style="font-size:11pt"><span><span>&quot;Thermal tolerance and adaptation in cnidarians: an investigation of host transcriptomic responses and heritable variation across natural populations&quot;</span></span></span></p>\r\n',
      featured: false,
      localist_url: 'https://events.oregonstate.edu/testo',
      localist_ics_url: 'https://events.oregonstate.edu/testo',
      photo_url: 'https://images.localist.com/photos/30443006289764/huge/testo.jpg',
      venue_url: 'https://events.oregonstate.edu/testo'
    }
  }
];

module.exports = { eventsData };
